[package]
name = "private-parts"
version = "0.1.0"
edition = "2024"

[dependencies]
private-parts-derive = { path = "./derive" }
rasn = "0.28.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"

